flat <- scores_export_1_
flat <- as.data.frame(subset(flat, select = c(folderno, test, score, percentile, admin)))
flat <- reshape(flat, direction = "wide",
                timevar = "test",
                idvar = "folderno")

colnames(flat)[2:82] <- c('score.Graphoria',
                    'percentile.Graphoria',
                    'admin.Graphoria',
                    'score.Ideaphoria',
                    'percentile.Ideaphoria',
                    'admin.Ideaphoria',
                    'score.Foresight',
                    'percentile.Foresight',
                    'admin.Foresight',
                    'score.InductiveReasoning',
                    'percentile.InductiveReasoning',
                    'admin.InductiveReasoning',
                    'score.AnalyticalReasoning',
                    'percentile.AnalyticalReasoning',
                    'admin.AnalyticalReasoning',
                    'score.NumericalReasoning',
                    'percentile.NumericalReasoning',
                   'admin.NumericalReasoning',
                    'score.NumberFacility',
                    'percentile.NumberFacility',
                    'admin.NumberFacility',
                    'score.WigglyBlock',
                    'percentile.WigglyBlock',
                    'admin.WigglyBlock',
                    'score.PaperFolding',
                    'percentile.PaperFolding',
                    'admin.PaperFolding',
                    'score.StructuralVisualization',
                    'percentile.StructuralVisualization',
                    'admin.StructuralVisualization',
                    'score.TonalMemory',
                    'percentile.TonalMemory',
                    'admin.TonalMemory',
                    'score.PitchDiscrimination',
                    'percentile.PitchDiscrimination',
                    'admin.PitchDiscrimination',
                    'score.RhythmMemory',
                    'percentile.RhythmMemory',
                    'admin.RhythmMemory',
                    'score.MemoryforDesign',
                    'percentile.MemoryforDesign',
                    'admin.MemoryforDesign',
                    'score.Silograms',
                    'percentile.Silograms',
                    'admin.Silograms',
                    'score.NumberMemory',
                    'percentile.NumberMemory',
                    'admin.NumberMemory',
                    'score.Observation',
                    'percentile.Observation',
                    'admin.Observation',
                    'score.Red-GreenVision',
                    'percentile.Red-GreenVision',
                    'admin.Red-GreenVision',
                    'score.ColorDiscrimination',
                    'percentile.ColorDiscrimination',
                    'admin.ColorDiscrimination',
                    'score.FingerDexterity',
                    'percentile.FingerDexterity',
                    'admin.FingerDexterity',
                    'score.TweezerDexterity',
                    'percentile.TweezerDexterity',
                    'admin.TweezerDexterity',
                    'score.WordAssociation',
                    'percentile.WordAssociation',
                    'admin.WordAssociation',
                    'score.EnglishVocabulary',
                    'percentile.EnglishVocabulary',
                    'admin.EnglishVocabulary',
                    'score.VisualDesigns1',
                    'percentile.VisualDesigns1',
                    'admin.VisualDesigns1',
                    'score.VisualDesigns2',
                    'percentile.VisualDesigns2',
                    'admin.VisualDesigns2',
                    'score.GripLeft',
                    'percentile.GripLeft',
                    'admin.GripLeft',
                    'score.GripRight',
                    'percentile.GripRight',
                    'admin.GripRight')


write.csv(flat, "Flat.csv")
